version: 2

sources:
  - name: application
    database: raw
    schema: application
    tables:
      - name: app_customers
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

      - name: app_employees
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

      - name: app_products
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}

      - name: app_sales
        loaded_at_field: loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}


models:
  - name: stg_application__customers
    columns:
      - name: id
        description: ""
        tests:
          - unique
          - not_null
      - name: ssn
        description: ""
        tests:
          - unique
      - name: first_name
        description: ""
      - name: last_name
        description: ""
      - name: email
        description: ""
      - name: phone
        description: ""
      - name: job_title
        description: ""
      - name: country
        description: ""
      - name: state
        description: ""
      - name: city
        description: ""
      - name: shipping_address
        description: ""
      - name: business_address
        description: ""

  - name: stg_application__employees
    columns:
      - name: id
        description: ""
        tests:
          - unique
          - not_null
      - name: ssn
        description: ""
        tests:
          - unique
          - not_null
      - name: first_name
        description: ""
      - name: last_name
        description: ""
      - name: email
        description: ""
      - name: phone
        description: ""
      - name: job_title
        description: ""
      - name: country
        description: ""
      - name: state
        description: ""
      - name: city
        description: ""
      - name: shipping_address
        description: ""
      - name: business_address
        description: ""
      - name: job_skill
        description: ""
      - name: pin
        description: ""
      - name: university_name
        description: ""
      - name: ip_address
        description: ""
      - name: adminission_datetime
        description: ""
      - name: deactivation_datetime
        description: ""

  - name: stg_application__products
    columns:
      - name: id
        description: ""
        tests:
          - unique
          - not_null
      - name: brand
        description: ""
      - name: size
        description: ""
      - name: collection
        description: ""
      - name: color
        description: ""
      - name: price
        description: ""
      - name: currency
        description: ""


  - name: stg_application__sales
    columns:
      - name: id
        description: ""
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - not_null
        description: ""
      - name: product_id
        description: ""
        tests:
          - not_null
      - name: employee_id
        description: ""
      - name: quantity
        description: ""
        tests:
          - not_null
      - name: transaction_datetime
        description: ""
        tests:
          - not_null
      - name: payment_method
        description: ""
        tests:
          - not_null
